### ISSUE TITLE
Set up identity storage in database

### ISSUE THREAD

**Issue by TomasKvaraciejus** [BenasB/vu-psk#14]
Once the database is set up, tables relevant to user identity handling (e.g. user data and something related to authorization) should be added so that work can proceed on task [#6 (Add specific user page)](https://github.com/users/BenasB/projects/2/views/1?pane=issue&itemId=61722541)

**Comment by 6ar8nas** [comment]
Per what was decided in internal team chat, the database for the identity service would ideally be different from the recipes database, although we should be consistent in terms of RDBMS, which I think will be PostgreSQL.

**Comment by BenasB** [comment]
I'm thinking that the `User` entity should be pretty simple to start off with, you can start off with `Username`, `PasswordHash`
Probably we'll be best off with RBAC, so probably it's worth having a `Role` field (e.g. `Member`, `Admin`)
