### ISSUE TITLE
Tags/categories for recipes

### ISSUE THREAD

**Issue by BenasB** [BenasB/vu-psk#17]
Adjust the Recipe entity/context to include Tags/Categories. This should implement a many to many relationship from Recipes to Tags/Categories. If this is done after #9, adjust API as well.

Adjust `Recipes.Public` as needed

**Comment by adomas-vensas** [comment]
This is the initial structure for the `Tags` entity. It's as simple as it gets. As mentioned previously in issue #8, I removed the `Amount` property from the entity. I also skipped the intermediary table for the M:M relationship, as this diagram is self-explanatory.

![Image](https://github.com/BenasB/vu-psk/assets/90962230/15cdf172-129d-431d-998a-1c0002c7ac8f)
