### ISSUE TITLE
Display tags in front-end

### ISSUE THREAD

**Issue by 6ar8nas** [BenasB/vu-psk#20]
Prerequisite: #17.

Display actual tags information in front-end recipe related pages - new recipe creation, single recipe display page.

**Comment by BenasB** [comment]
I think I partially did this (at least the showing part) in #44

**Comment by 6ar8nas** [comment]
I think this covers it fully.

**Comment by 6ar8nas** [comment]
It looks like it doesn't. Once the linked PR is finished, I will make the remaining changes.
