### ISSUE TITLE
Add specific recipe page

### ISSUE THREAD

**Issue by BenasB** [BenasB/vu-psk#5]
Ideally done after #4, but can be done without the abstraction I guess
#9 will add the endpoint on Recipes API for retrieving a specific recipe, so until then, you can just get all recipes and let id be the index of that list 

On the front end, when navigated to `/recipes/:id`, a user should be presented a page with details about a specific recipe. For now, just output all of the data of the recipe (we'll come up with a better design/presentation down the line).

Please handle case in UI when the recipe can't be found by id.

in `/recipes` (the page that lists all recipe titles) make the titles links that would take you to the recipe's page.

Some [routing docs](https://learn.microsoft.com/en-us/aspnet/core/blazor/fundamentals/routing?view=aspnetcore-8.0) to start off

**Comment by 6ar8nas** [comment]
Waiting for #8 to be completed.
