### ISSUE TITLE
Write-up: 'Komandinio darbo ataskaita'

### ISSUE THREAD

**Issue by TomasKvaraciejus** [BenasB/vu-psk#51]
Write the group assignment team work and scrum processes report documentation.

The report's template is published in the Teams channel.

### Acceptance criteria

A team work and scrum process report deliverable finished.

**Comment by 6ar8nas** [comment]
The document looks good. Made some minor adjustments to emphasize a few in my opinion important details, but overall solid. Closing it as done.
